%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: D:\gdialynas\Desktop\My files\Oscilation data\Osci1.xlsx
%    Worksheet: output1
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2017/02/01 15:59:32

%% Import the data
[~, ~, raw] = xlsread('D:\gdialynas\Desktop\My files\Oscilation data\Osci1.xlsx','output1','A2:G10791');
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};
cellVectors = raw(:,7);
raw = raw(:,[1,2,3,4,5,6]);

%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),raw); % Find non-numeric cells
raw(R) = {NaN}; % Replace non-numeric cells

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Allocate imported array to column variable names
Timer = data(:,1);
T = data(:,2);
EncCounts = data(:,3);
D = data(:,4);
DEG = data(:,5);
Rad = data(:,6);
VarName7 = cellVectors(:,1);
%% Plot
%figure
%findpeaks(DEG); % 36 to 46
%text(locs+.02,pks,num2str((1:numel(pks))'))
%plot(T,pks);
%axis([0 10.791 -15 15])
%plot
figure
plot(T,DEG)
axis([0 10.791 -15 15])
title('Oscillation of steering column weights')
xlabel('Time(s)') % x-axis label
ylabel('Angle (deg)') % y-axis label
%% Calculation of mass moment of inertia
%find peaks and time intervals after spring extension & when oscilationstop
[pks,locs]=findpeaks(DEG);
idx=locs(locs>=4643 & locs<=10020);
B=idx;
Time=T(B);
Timenew=diff(Time);
period=mean(Timenew);%Period of oscillation(s)
%Angular frequency
p=3.14;
w=2*p/period;
% mass moment of inertia
K=315; % N/M spring constant for both springs
a=0.29; % M distance between spring and center of stem
I=K*0.29^2/w^2;% kgm^2