%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: D:\gdialynas\Desktop\My files\Oscilation data\Osci2.xlsx
%    Worksheet: output6
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2017/02/01 14:15:44

%% Import the data
[~, ~, raw] = xlsread('D:\gdialynas\Desktop\My files\Oscilation data\Osci2.xlsx','output6','A2:E7822');
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};
cellVectors = raw(:,1);
raw = raw(:,[2,3,4,5]);

%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),raw); % Find non-numeric cells
raw(R) = {NaN}; % Replace non-numeric cells

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Allocate imported array to column variable names
Timer = cellVectors(:,1);
Time = data(:,1);
Counts = data(:,2);
Deg = data(:,3);
Degc = data(:,4);

%% Clear temporary variables
clearvars data raw cellVectors R;
%% Plot 
%figure
%findpeaks(Degc);
%text(locs+.02,pks,num2str((1:numel(pks))'))
%plot(Time,pks);
%axis([0 7.8 -15 15])
%% Plot
plot(Time,Degc)
title('Oscillation of steering column without weights')
xlabel('Time(s)') % x-axis label
ylabel('Angle (deg)') % y-axis label
%% Calculation of mass moment of inertia
%find peaks and time intervals after spring extension & when oscilationstop
[pks,locs]=findpeaks(Degc);
idx=locs(locs>=3853 & locs<=6980); % 13 to 22
B=idx;
T=Time(B);
Timenew=diff(T);
period=mean(Timenew);%Period of oscillation(s)
%Angular frequency
p=3.14;
w=2*p/period;
% mass moment of inertia
K=315; % N/M spring constant for both springs
a=0.29; % M distance between spring and center of stem
I=K*0.29^2/w^2;% kgm^2
%Notes
%idx=find(Deg>300);
%Deg(idx)=Deg(idx)-360;
%Deg(Deg>300)=Deg(Deg>300)-360
